import os
from pathlib import Path

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "REMPLACE_PAR_TON_TOKEN")

ALLOWED_CHAT_IDS = set()

WINAMAX_POLL_INTERVAL_S = 60
LIVE_UPDATE_INTERVAL_S  = 90
PREMATCH_ALERT_CHECK_S  = 300

PREMATCH_WINDOW_HOURS   = 3
MIN_CONFIDENCE_ALERT    = 50
WINAMAX_CAPTURE_S       = 60
MAX_LIVE_MATCHES        = 8

ROOT_DIR  = Path(__file__).parent
DATA_DIR  = ROOT_DIR / "data"
LOG_DIR   = ROOT_DIR / "logs"
CACHE_MAX_AGE_S = 300

PROXY_URL = None

MAX_MESSAGE_LENGTH = 4000
